// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "../src/Zora.js";
import * as Caml_option from "../node_modules/rescript/lib/es6/caml_option.js";

function $$default(t) {
  t.equal(42, 42, "Numbers are equal");
  t.notEqual(42, 43, "Numbers are not equal");
  var x = {
    hello: "world"
  };
  var z = {
    hello: "world"
  };
  t.is(x, x, "object is object");
  t.is(x, x, "object is object");
  t.isNot(x, z, "object is not object with same values");
  t.equal(x, z, "Object is deep equal");
  t.ok(true, "boolean is ok");
  t.notOk(false, "boolean is not ok");
  Zora.$$Option.none(t, undefined, "None is None");
  Zora.$$Option.some(t, Caml_option.some(x), "option is Some");
  Zora.Result.error(t, {
        TAG: /* Error */1,
        _0: x
      }, "Is Error Result");
  Zora.Result.ok(t, {
        TAG: /* Ok */0,
        _0: x
      }, "Is Ok Result");
  return Zora.done(undefined);
}

export {
  $$default ,
  $$default as default,
  
}
/* No side effect */
