// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";

Zora.test("Should run some simple blocking tests", (function (t) {
        t.test("should greet", (function (t) {
                t.ok(true, "hello world");
              }));
        t.test("should answer question", (function (t) {
                t.equal(42, 42, "should be 42");
              }));
      }));

export {
  
}
/*  Not a pure module */
