// Generated by ReScript, PLEASE EDIT WITH CARE


function $$default(t) {
  t.test("should greet", (function (t) {
          t.ok(true, "hello world");
          
        }));
  t.test("should answer question", (function (t) {
          t.equal(42, 42, "should be 42");
          
        }));
  
}

export {
  $$default ,
  $$default as default,
  
}
/* No side effect */
