// Generated by ReScript, PLEASE EDIT WITH CARE


import {test} from 'zora'

test('should result to the answer', t => {
    const answer = 42;
    t.equal(answer, 42, 'answer should be 42');
});
;

export {
  
}
/*  Not a pure module */
