// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "../src/Zora.js";

function $$default(t) {
  t.skip("broken test", (function (t) {
          t.fail("Test is broken");
          return Zora.done(undefined);
        }));
  t.skip("also broken", (function (t) {
          t.fail("Test is broken, too");
          
        }));
  return Zora.done(undefined);
}

export {
  $$default ,
  $$default as default,
  
}
/* No side effect */
