// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "../src/Zora.mjs";
import * as Zora$1 from "zora";

Zora$1.test("should skip some tests", (function (t) {
        t.skip("broken test", (function (t) {
                t.fail("Test is broken");
                return Zora.done(undefined);
              }));
        t.skip("also broken", (function (t) {
                t.fail("Test is broken, too");
                
              }));
        return Zora.done(undefined);
      }));

export {
  
}
/*  Not a pure module */
