// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";

Zora.test("should skip some tests", (async function (t) {
        t.skip("broken test", (async function (t) {
                t.fail("Test is broken");
              }));
        t.skip("also broken", (function (t) {
                t.fail("Test is broken, too");
              }));
      }));

export {
  
}
/*  Not a pure module */
