// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";

Zora.test("should run a test asynchronously", (async function (t) {
        t.equal(42, 42, "Should answer the question");
      }));

Zora.test("should run a second test at the same time", (async function (t) {
        t.equal(3.14, 3.14, "Should be a tasty dessert");
      }));

export {
  
}
/*  Not a pure module */
