// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "../src/Zora.js";
import * as Zora$1 from "zora";

Zora$1.test("should run a test asynchronously", (function (t) {
        t.equal(42, 42, "Should answer the question");
        return Zora.done(undefined);
      }));

Zora$1.test("should run a second test at the same time", (function (t) {
        t.equal(3.14, 3.14, "Should be a tasty dessert");
        return Zora.done(undefined);
      }));

export {
  
}
/*  Not a pure module */
