// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "../node_modules/rescript/lib/es6/curry.js";

function $$then(prim0, prim1) {
  return prim0.then(Curry.__1(prim1));
}

function done(prim) {
  return Promise.resolve(prim);
}

export {
  $$then ,
  done ,
  
}
/* No side effect */
