// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "../node_modules/rescript/lib/es6/curry.js";
import * as Belt_Option from "../node_modules/rescript/lib/es6/belt_Option.js";
import * as Belt_Result from "../node_modules/rescript/lib/es6/belt_Result.js";
import * as Caml_option from "../node_modules/rescript/lib/es6/caml_option.js";

function optionNone(zora, actual, message) {
  zora.ok(Belt_Option.isNone(actual), message);
}

function optionSome(zora, actual, check) {
  if (actual !== undefined) {
    return Curry._2(check, zora, Caml_option.valFromOption(actual));
  } else {
    zora.fail("Expected Some value, got None");
    return ;
  }
}

function resultError(zora, actual, message) {
  zora.ok(Belt_Result.isError(actual), message);
}

function resultOk(zora, actual, check) {
  if (actual.TAG === /* Ok */0) {
    return Curry._2(check, zora, actual._0);
  }
  zora.fail("Expected ok value, got error");
}

export {
  optionNone ,
  optionSome ,
  resultError ,
  resultOk ,
}
/* No side effect */
